MODEL:
  TYPE: vmamba2
  NAME: vssd_tiny_e300
  DROP_PATH_RATE: 0.2
  VMAMBA2:
    EMBED_DIM: 64
    DEPTHS: [ 2, 4, 8, 4]
    NUM_HEADS: [2, 4, 8, 16]
    SIMPLE_DOWNSAMPLE: False
    SIMPLE_PATCH_EMBED: False
    SSD_EXPANSION: 2
    SSD_CHUNK_SIZE: 256
    LINEAR_ATTN_DUALITY: True
    #SSD_POSITIVE_DA: True
    ATTN_TYPES: ['mamba2', 'mamba2', 'mamba2', 'standard']

  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  #MESA: 1.0 if using MESA

#24.27M 4.47G
