MODEL:
  TYPE: vmamba2
  NAME: vssd_micro_e300
  DROP_PATH_RATE: 0.1
  VMAMBA2:
    EMBED_DIM: 48
    DEPTHS: [ 2, 2, 8, 4]
    NUM_HEADS: [2, 4, 8, 16]
    SIMPLE_DOWNSAMPLE: False
    SIMPLE_PATCH_EMBED: False
    SSD_EXPANSION: 2
    SSD_CHUNK_SIZE: 256
    LINEAR_ATTN_DUALITY: True
    SSD_POSITIVE_DA: True
    ATTN_TYPES: ['mamba2', 'mamba2', 'mamba2', 'standard']
    D_STATE: 48

  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20

#13.5M 2.3GFLOP